### ISSUE TITLE
Loading SVG files fails

### ISSUE THREAD

**Issue by manyids2** [jupyterlab/theme-cookiecutter#2]
I think the cookiecutter version only serves files in the root, while icons, etc are deeper down, also
perhaps missing some types (svg, png, etc)
From package.json:

```
cookiecutter version:
    "style/*.css",
    "style/*.ttf",
    "style/*.eot",
    "style/*.woff",
    "style/*.woff2"
```

```
theme-light-extension version:
    "style/**/*.{css,eot,gif,html,jpg,json,png,svg,woff2,ttf}"

```

**Comment by telamonian** [comment]
This is a duplicate of the issue discussed in jupyterlab/theme-cookiecutter-ts#5
