### ISSUE TITLE
To archive

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/theme-cookiecutter#25]
Follow-up Pr

> To reduce maintenance burden this merge https://github.com/jupyterlab/theme-cookiecutter

+1, since the theme cookiecutter can easily get out of sync and doesn't necessarily benefit from the improvements made to the ts cookiecutter here (for example CI and releaser config).

Some follow-up steps that come to mind:

- Archive: https://github.com/jupyterlab/theme-cookiecutter
- Update the extension tutorial
- Update the apod repo

_Originally posted by @jtpio in https://github.com/jupyterlab/extension-cookiecutter-ts/issues/196#issuecomment-1012391791_

**Comment by jtpio** [comment]
Fixed by https://github.com/jupyterlab/theme-cookiecutter/pull/26
