### ISSUE TITLE
"style/*.foo" globs in package.json too specific

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/theme-cookiecutter#5]
First I'd like to say thank you for putting this together. I'd been searching for a while now for a way to make my custom theme work.  From what I've seen, this is necessary for the icons to work with a custom theme. The install, and subsequent rebuild doesn't seem to copy over the svg files so the console is littered with 404's but having it run through webpack obviously doesn't have this issue.

_Originally posted by @mountain01 in https://github.com/jupyterlab/theme-cookiecutter-ts/pull/1#issuecomment-459814700_

The issue that @mountain01 pointed out is actually separate from the webpack discussion. The file specifiers in the `package.json` template are too specific, and so miss certain files.

**Comment by ian-r-rose** [comment]
This should be fixed by #3

**Comment by telamonian** [comment]
@ian-r-rose I saw! Thanks
